#ifndef NAMMA_AUTOSAR_ETHIF_CFG_H
#define NAMMA_AUTOSAR_ETHIF_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Platform_Types.h>



typedef struct {
        uint8   max_trcvs;
        boolean dev_error_detect;
        boolean en_rx_int;
        boolean en_tx_int;
        boolean version_info_api;
        boolean version_info_api_macro;
        uint8 lnk_st_ch_mn_reload;
        uint16  mn_fn_period_ms;
        uint16  rx_ind_itrtn;
        boolean get_rst_meas_data_api;
        boolean start_auto_neg;
        boolean get_baud_rate;
        boolean counter_state;
        boolean gl_time_supp;
        boolean wake_supp;
        boolean trcv_wakemode_api;
        uint16  swt_off_port_delay_ms;
        uint16  port_startup_activ_ms;
        uint16  mn_fn_state_period_ms;
        boolean set_fwd_mode_api;
        boolean verify_cfg_api;
        boolean swt_mgmt_supp;
        boolean get_ctrl_idx_lst;
        boolean get_vlan_id_supp;
        boolean en_weth_api;
        boolean en_sig_qual_api;
        uint16  sig_qual_chk_ms;
        boolean en_sec_evt_report;
        void *sec_evt_ref;
} EthIfGeneralCfgType;



typedef struct {
        const EthIfGeneralCfgType general;
} EthIf_ConfigType;



extern const EthIf_ConfigType EthIfConfigs;


#endif
